DROP TABLE IF EXISTS envio CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS detalle_cliente CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS repartidor CASCADE;
DROP TABLE IF EXISTS empresa_reparto CASCADE;
DROP TABLE IF EXISTS producto CASCADE;